[project]
name = "qt-lms"
version = "0.1.0"
description = "Library Management System using Pyside6"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic[email]>=2.11.5",
    "pyside6>=6.9.1",
]
